# Generated by Django 4.0.2 on 2022-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
